### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by EmilieYZhang**
**Added database and application unittests**
_Database testing - test_db.py_
- Set up sqlite in-memory database for testing
- Assert creation of timeline posts: 'John Doe' and 'Jane Doe'
- Assert the two posts have correct ids of 1 and 2 respectively
- Assert that they are correctly added
- Assert the length of timeline is 2 posts as expected
- Assert the corresponding names of the 2 posts are 'John Doe' and 'Jane Doe' by using get endpoint

_Application testing - test_app.py_
- Tested homepage: title is 'Emily Lim' and meta tags are set correctly
- Test timeline: 2 POST requests
- Test the POST requests was successfully added by status code
- Test timeline: GET request, check that length of timeline-posts is 2
- Check the two posts have correct expected id and name
- Test timeline page: title is 'Timeline' and there are input fields for a POST request
- Test edge cases/invalid inputs
- Assert 400 error is thrown for invalid inputs:
       - Testcase 1: Missing 'name' parameter
       - Testcase 2: 'email' input missing @ sign
       - Testcase 3: 'content' has empty string as input
 
_EXTRA: Alert system in timeline.html_
- Added a function in the javascript of the timeline page to alert invalid inputs

### CODE REVIEW

**Comment by EmilieYZhang** [comment]
While testing, I noticed the title for the timeline page happens to be 'Document', do you want to leave that as is or do you want me to change it to something else?

**Comment by emilyllim** [comment]
Yes you can change it, that should be "Timeline". Thanks for catching that!

**Comment by EmilieYZhang** [comment]
Sure, did a simple fix on the timeline page title, all good now! Let me know if there are other changes to be made.

**Review by emilyllim — APPROVED** [review]
I'll merge it now, everything looks good! Thanks for adding the alert feature!

**Pull request merged**
